redis:
  enabled: true
spring:
  redis:
    database: ${redis.database:0}
    host: ${redis.host:localhost}
    port: ${redis.port:6379}
    password: ${redis.password:}
    cluster:
      nodes: ${redis.cluster.nodes:}
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: ${redis.pool.max-active:8}
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: ${redis.pool.max-wait:-1}
      # 连接池中的最大空闲连接
      max-idle: ${redis.pool.max-idle:8}
      # 连接池中的最小空闲连接
      min-idle: ${redis.pool.min-idle:0}
      # 连接超时时间（毫秒）
      timeout: ${redis.pool.timeout:0}
